CAPSTONE/
  __init__.py
  main.py
  controller/
    AccounController.py
    AccountController.test.py
  repository/
    AccountRepository.py
    AccountRepository.test.py
  service/
    AccountService.py
    AccountService.test.py
  util/
    DBConnect.py
  model/
    Account.py
  tests/
    test_account_repository.py
    test_address_repository.py